### PR TITLE
updated to Twilio Android 5.8.1 #9

### PR DESCRIPTION
**Pull request by jtorvald**
I upgraded to Twilio Video Android 5.8.1
https://github.com/dkornev/TwilioVideoXamarinAndroid/issues/9

### CODE REVIEW

**Comment by dkornev** [comment]
Sweet! Thank you very much for your efforts. Looks solid at a glance. I'll review it tonight

**Comment by jtorvald** [comment]
No problem at all. It's the least I can do after all your work on these bindings. Let me know if there are issues.

**Comment by jtorvald** [comment]
@dkornev I don't undestand your question. What I did is to add the new .aar and renamed the namespace from org.webrtc to tvi.webrtc That's it. I tested it with referencing the project to my video project and run it. That worked.

**Comment by dkornev** [comment]
@dkornev In the previous version of Twilio SDK in *.aar there was an XML attribute missing (video-android-*.aar/res/values/values.xml) so I had to unzip the *.aar, add the missing attribute and assemble it into a new *.aar file manually. For some reason, it was working with android gradle but not with xamarin.

> $ unzip video-android-4.3.1.aar -d tempFolder    
> Change whatever you need    
>$ jar cvf video-android-4.3.1.aar -C tempFolder/ .

I see that now it's already there and no need to add it.

**FYI:**
Now I can't build my project because of the following error:

> Error XA1014: JAR library references with identical file names but different contents were found: libwebrtc.jar. Please 
> remove any conflicting libraries from EmbeddedJar, InputJar and AndroidJavaLibrary.

 
So I'll do one more thing. I'll rename /src/Jars/*.aar/libs/libwebrtc.jar to libwebrtc_2.jar so it will be possible to use Twilio.Voice and Twilio.Video SDKs in the same project.

**Comment by jtorvald** [comment]
@dkornev okay good to know. Yeah I was already wondering about the _2.jar being different. I understand why you did that now. I will do that next time as well.

**Pull request merged**
