### PR TITLE
Updated to 5.13.0

### PR DESCRIPTION
**Pull request by jtorvald**
renamed libs/libwebrtc.jar to libwebrtc_2.jar

### CODE REVIEW

**Comment by dkornev** [comment]
Looks solid! Thank you @jtorvald 
I'll build the package later.

**Comment by jtorvald** [comment]
You're welcome! I will try to see if I can find some time to take on 6.X but I guess that will be a bigger fish to fry.
Bringing 5 to the latest release was a good exercise. Do you think you can manage to build the package in the coming week?

**Comment by jtorvald** [comment]
@dkornev I tried 6.2 but I get this:
/src/TwilioVideo.Camera2Capturer.cs(67,67): Error CS0535: 'Camera2Capturer' does not implement interface member 'IVideoCapturer.ChangeCaptureFormat(int, int, int)' (CS0535) (Twilio.Video.Android)

I don't know what to change in MetaData to make this work. I tried various things.

The generated code has an interface (IVideoCapturerInvoker) that has the method: 
```
public unsafe void ChangeCaptureFormat (int p0, int p1, int p2)
		{
			// code...
		}
```
But that method is not generated in: Camera2Capturer
If I know how to annotate that in the XML I might be able to continue.

**Comment by dkornev** [comment]
MetaData has been always a tricky part of the android binding process. I'll take a look at the weekend

**Comment by jtorvald** [comment]
@dkornev super! Yeah it looks like magic....  Would be interesting to know how it works so I can fix this stuff myself.

**Pull request merged**
