### PR TITLE
Updated to twilio video 6.2.0

### PR DESCRIPTION
**Pull request by guillermo-gerard**
Hi @dkornev 
Thank you for your work in this project. 
I've updated it with the twilio video SDK 6.2.0 
@jtorvald already performed a basic test and it appears to be working as expected

### CODE REVIEW

**Comment by jtorvald** [comment]
I tried upgrading to 6.2 but ran into issues. Thankfully @guillermo-gerard) was there to help out and fixed the binding issues. I just tested it in my project and it seems to work for the video calling part. I think @guillermo-gerard did not rename the libwebrtc.jar to libwebrtc_2.jar. I just asked him if he could fix that in the pull request.

I haven't tested screensharing yet because that takes extra time with other Android issues due to newer SDK's.

Be aware that there are API changes. Migration from 5 to 6 is quite easy with the help of Twilio's documentation on migration:
[https://www.twilio.com/docs/video/migrating-5x-6x](https://www.twilio.com/docs/video/migrating-5x-6x)

**Comment by dkornev** [comment]
Great work guys. 
Thank you for your contribution, we moved from Xamarin.Android to Kotlin and that's the reason why I put even fewer efforts into this binding than I did before. I appreciate your help.

At a glance, everything looks solid. I'll review it one more time + I'll build the NuGet package once I have some spare time. Probably on the weekend.

**Comment by jtorvald** [comment]
@dkornev could you please also make a nuget for the 5.13.0 version just in case the 6.2.0 has issues? So I can quickly switch back to the newest 5 version?

**Comment by 4brunu** [comment]
Any news on this? Looking forward to use the new version 😊

**Comment by jtorvald** [comment]
@dkornev Is there anything that I can help with to speed this up?

**Comment by dkornev** [comment]
@jtorvald , @4brunu 
Hey folks.
FYI, working on it right now

**Comment by dkornev** [comment]
I've finally updated the SDK to v6.2.1.
https://github.com/dkornev/TwilioVideoXamarinAndroid/releases/tag/v6.2.1.0
https://www.nuget.org/packages/Twilio.Video.Android.XamarinBinding/6.2.1

I've tested it using my old Xamarin application and video calls work perfectly.

@guillermo-gerard and @jtorvald , @4brunu Thank you very much for your patience. Let me know which binding you want me to update next.

**Comment by jtorvald** [comment]
@dkornev thank you very much! I'll send you a pull request when I do another version. If I can't figure it out, I will ask @guillermo-gerard if he wants to help out.

**Comment by 4brunu** [comment]
Thank you all for the help.
It would be nice if the iOS version would also be updated :)

**Pull request merged**
